### ISSUE TITLE
Stop using `pkg-ci-scripts` in all gap-actions

### ISSUE THREAD

**Issue by fingolfin** [gap-actions/setup-gap#25]
(I am abusing this as a kind of meta issue tracker for all of gap-actions).

Right now we are still using the scripts in https://github.com/gap-system/pkg-ci-scripts . I think we should stop doing that and instead incorporate that code directly into the various actions here. 

Because right now, we can't really version our actions, unless we switch from just cloning pkg-ci-scripts to cloning a specific commit there; but since we only clone it once, in setup-gap, we then must coordinate any change to a newer commit with all actions.

Plus, some things that perhaps made sense in the old actions when they were used with Travis make far less sense now.

We can do this incrementally, of course: first convert all other actions, one by one; and when the last one switched away, we can stop cloning that repository here.

Related PRs:
- https://github.com/gap-actions/build-pkg/pull/4
- https://github.com/gap-actions/process-coverage/pull/7
- https://github.com/gap-actions/run-pkg-tests/pull/10
- https://github.com/gap-actions/setup-gap/pull/30

**Comment by wilfwilson** [comment]
Okay, good idea.
